amazon:
  aws:
    accesskey: AKIA4UATCKVQEQOG3OWP
    region:  us-east-2
    secretkey: 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
  dynamodb:
    endpoint: 'dynamodb.us-east-2.amazonaws.com'
server:
  port: 8091